version: "3.8"
services:
  web:
    container_name: "web_2"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: sh -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/web
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/admin
      - SECRET_KEY=2e2406f8eb7862f9d8f8f0f8411a15f26b8b201391df8a77ccc90
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine3.18
    hostname: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin

